version: '3.8'

services:
  books-iam:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=books-service
    command: npm run start:dev -- books-iam # This instructs Docker Compose to run the "start:dev" script when starting the container
    environment:
      # Here we specify the environment variables that will be passed to the container
      - BOOK_DB_HOST=books-db
      - BOOK_DB_PORT=5432
      - BOOK_DB_USER=postgres
      - BOOK_DB_PASSWORD=postgres
      - BOOK_DB_NAME=books
    deploy:
      replicas: 1 # This instructs Docker Compose to start 3 instances of the "books-iam" container
    volumes:
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      # Note: This is usually not a good practice to mount the "node_modules" directory on the host to the container       # We are doing this for the sake of simplicity in this example       - ./node_modules:/usr/src/app/node_modules
      # This instructs Docker Compose to mount the "books-iam" directory on the host to the "/usr/src/app" directory on the container
      # This allows us to make changes to the code on the host and have them reflected in the container without having to rebuild the image
      - ./apps/books-iam:/usr/src/app/apps/books-iam
    depends_on:
      - books-db
      - books-service
  books-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=books-service
    command: npm run start:dev -- books-service # This instructs Docker Compose to run the "start:dev" script when starting the container
    environment:
      # Here we specify the environment variables that will be passed to the container
      - BOOK_DB_HOST=books-db
      - BOOK_DB_PORT=5432
      - BOOK_DB_USER=postgres
      - BOOK_DB_PASSWORD=postgres
      - BOOK_DB_NAME=books
    deploy:
      replicas: 1 # This instructs Docker Compose to start 3 instances of the "books-service" container
    volumes:
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      # Note: This is usually not a good practice to mount the "node_modules" directory on the host to the container       # We are doing this for the sake of simplicity in this example       - ./node_modules:/usr/src/app/node_modules
      # This instructs Docker Compose to mount the "books-service" directory on the host to the "/usr/src/app" directory on the container
      # This allows us to make changes to the code on the host and have them reflected in the container without having to rebuild the image
      - ./apps/books-service:/usr/src/app/apps/books-service
    depends_on:
      - books-db
  books-db:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=books